# This workflow use the Docker login-action, metadata-action, and build-push-action
# actions to build the Docker images, and if the build succeeds, push the built image
# to GitHub Packages.

name: Pulls and publish docker images to Github Packages

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ['main']

# Defines two custom environment variables for the workflow. These are used for the Container
# registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}
  IMAGE_NAME: tek24-stack

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Uses the `docker/login-action` action to log in to the Container registry
      # using the account and password that will publish the packages.
      # Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      #
      - name: Build dockers
        run: |
          docker compose -f ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/compose.yml build
     

# CMD tail -f /dev/null